apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: defult
  labels:
    name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-app
  template:
    metadata:
      labels:
        name: go-app
    spec:
      containers:
      - name: go-app
        image: amrmohamady/hello-go:latest
        imagePullPolicy: IfNotPresent
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
         tcpSocket:
            port: 8080
         initialDelaySeconds: 60
         timeoutSeconds: 10
        livenessProbe:
         tcpSocket:
             port: 8080
         initialDelaySeconds: 60
         timeoutSeconds: 15
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: defult
  labels:
    name: go-app
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    name: go-app
